
package UI;

import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import logic.*;

/*
    Elaborado por:
      Diana Decena
      Jose Alguindigue
*/

public class UI extends javax.swing.JFrame {

    private Fabrica fabrica;
    private int cont = 0;
    
    public UI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        //Crear fábrica 
        fabrica = new Fabrica();
        
        //Párametros iniciales para la interfaz gráfica
        this.inicializarParametros();
        
        contratarPRuedas.setVisible(false);
        contratarPParabrisas.setVisible(false);
        contratarPMotores.setVisible(false);
        despedirPRuedas.setVisible(false);
        despedirPParabrisas.setVisible(false);
        despedirPMotores.setVisible(false);
        contratarEnsambladores.setVisible(false);
        despedirEnsambladores.setVisible(false);
                    

        //Actualizar interfaz gráfica 
        Timer timer = new Timer(1, (ActionEvent ae) -> {  
            //set cantidades iniciales
            cantPRuedas.setText(Integer.toString(fabrica.getCantProductoresR()));
            cantPParabrisas.setText(Integer.toString(fabrica.getCantProductoresP()));
            cantPMotores.setText(Integer.toString(fabrica.getCantProductoresM()));
            cantEnsambladores.setText(Integer.toString(fabrica.getCantEnsambladores()));
            cantParabrisas.setText(Integer.toString(Fabrica.cantParabrisas));
            cantRuedas.setText(Integer.toString(Fabrica.cantRuedas));
            cantMotores.setText(Integer.toString(Fabrica.cantMotores));
            cantCarros.setText(Integer.toString(Fabrica.getCarrosTerminados()));
            cantDias.setText(Integer.toString(Jefe.getDiasDespacho()));
            estadoJefe.setText(Jefe.estado);
            gerenteEstado.setText(Gerente.estado);
            
            if(Fabrica.carrosTerminados == 0){
                carros.setIcon(new ImageIcon(getClass().getResource("carros-off.png")));
            } else {
                carros.setIcon(new ImageIcon(getClass().getResource("carros-on.png")));
            }
            
            if(Jefe.getEstado() == "durmiendo"){
                etiqueta1.setIcon(new ImageIcon(getClass().getResource("no-jefe-gerente.png")));
            } else {
                etiqueta1.setIcon(new ImageIcon(getClass().getResource("jefe-gerente-on.png")));
            }
            
            if(Gerente.getEstado() == "durmiendo"){
                etiqueta2.setIcon(new ImageIcon(getClass().getResource("no-jefe-gerente.png")));
            } else {
                etiqueta2.setIcon(new ImageIcon(getClass().getResource("jefe-gerente-on.png")));
            }
            
            if(Jefe.getDiasDespacho() > 9){
                cantDias.setLocation(910, 380);
            } else {
                cantDias.setLocation(930, 380);
            }
            
            if(Fabrica.carrosTerminados  > 9){
                cantCarros.setLocation(920, 240);
            } else {
                cantCarros.setLocation(930, 240);
            }
            
        });
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JPanel();
        texto8 = new javax.swing.JLabel();
        cantDias = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        textoCarros = new javax.swing.JLabel();
        cantCarros = new javax.swing.JLabel();
        carros = new javax.swing.JLabel();
        dias = new javax.swing.JLabel();
        cantPRuedas = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        cantEnsambladores = new javax.swing.JLabel();
        cantRuedas = new javax.swing.JLabel();
        ruedas = new javax.swing.JLabel();
        cantParabrisas = new javax.swing.JLabel();
        parabrisas = new javax.swing.JLabel();
        cantMotores = new javax.swing.JLabel();
        motores = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        productoresRuedas = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        cantPParabrisas = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        productoresParabrisas = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        cantPMotores = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        productoresMotores = new javax.swing.JLabel();
        ensambladores = new javax.swing.JLabel();
        despedirPRuedas = new javax.swing.JLabel();
        despedirPParabrisas = new javax.swing.JLabel();
        despedirPMotores = new javax.swing.JLabel();
        contratarPParabrisas = new javax.swing.JButton();
        contratarPRuedas = new javax.swing.JButton();
        contratarPMotores = new javax.swing.JButton();
        despedirEnsambladores = new javax.swing.JLabel();
        contratarEnsambladores = new javax.swing.JButton();
        gerente = new javax.swing.JLabel();
        jefe = new javax.swing.JLabel();
        estadoJefe = new javax.swing.JLabel();
        etiqueta1 = new javax.swing.JLabel();
        gerenteEstado = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard.setBackground(new java.awt.Color(13, 20, 74));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        texto8.setForeground(new java.awt.Color(204, 204, 204));
        texto8.setText("DIAS");
        dashboard.add(texto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, -1, -1));

        cantDias.setFont(new java.awt.Font("Segoe UI", 1, 75)); // NOI18N
        cantDias.setForeground(new java.awt.Color(255, 255, 255));
        cantDias.setText("30");
        dashboard.add(cantDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 100, 150));

        texto1.setBackground(new java.awt.Color(112, 112, 112));
        texto1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto1.setForeground(new java.awt.Color(204, 204, 204));
        texto1.setText("PRODUCTORES");
        dashboard.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 130, 30));

        textoCarros.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textoCarros.setForeground(new java.awt.Color(204, 204, 204));
        textoCarros.setText("CARROS PRODUCIDOS");
        dashboard.add(textoCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 200, -1));

        cantCarros.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        cantCarros.setForeground(new java.awt.Color(255, 255, 255));
        cantCarros.setText("10");
        dashboard.add(cantCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 60, -1));

        carros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/carros-off.png"))); // NOI18N
        dashboard.add(carros, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        dias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/dias.png"))); // NOI18N
        dashboard.add(dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        cantPRuedas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantPRuedas.setForeground(new java.awt.Color(255, 255, 255));
        cantPRuedas.setText("2");
        dashboard.add(cantPRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 30, -1));

        texto7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto7.setForeground(new java.awt.Color(204, 204, 204));
        texto7.setText("ENSAMBLADORES");
        dashboard.add(texto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        cantEnsambladores.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        cantEnsambladores.setForeground(new java.awt.Color(255, 255, 255));
        cantEnsambladores.setText("3");
        dashboard.add(cantEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 330, 30, -1));

        cantRuedas.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        cantRuedas.setForeground(new java.awt.Color(24, 24, 24));
        cantRuedas.setText("15");
        dashboard.add(cantRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        ruedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/ruedas.png"))); // NOI18N
        dashboard.add(ruedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        cantParabrisas.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        cantParabrisas.setForeground(new java.awt.Color(24, 24, 24));
        cantParabrisas.setText("9");
        dashboard.add(cantParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        parabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/parabrisas.png"))); // NOI18N
        dashboard.add(parabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 300, -1));

        cantMotores.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        cantMotores.setForeground(new java.awt.Color(24, 24, 24));
        cantMotores.setText("10");
        dashboard.add(cantMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 90, -1));

        motores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/motores.png"))); // NOI18N
        dashboard.add(motores, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        texto2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto2.setForeground(new java.awt.Color(204, 204, 204));
        texto2.setText("RUEDAS");
        dashboard.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 326, 60, 20));

        productoresRuedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/p50.png"))); // NOI18N
        dashboard.add(productoresRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, -1));

        texto4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto4.setForeground(new java.awt.Color(204, 204, 204));
        texto4.setText("PARABRISAS");
        dashboard.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        cantPParabrisas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantPParabrisas.setForeground(new java.awt.Color(255, 255, 255));
        cantPParabrisas.setText("3");
        dashboard.add(cantPParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 340, 30, -1));

        texto3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto3.setForeground(new java.awt.Color(204, 204, 204));
        texto3.setText("PRODUCTORES");
        dashboard.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        productoresParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/p3.png"))); // NOI18N
        dashboard.add(productoresParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        texto5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto5.setForeground(new java.awt.Color(204, 204, 204));
        texto5.setText("PRODUCTORES");
        dashboard.add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        cantPMotores.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantPMotores.setForeground(new java.awt.Color(255, 255, 255));
        cantPMotores.setText("1");
        dashboard.add(cantPMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 40, -1));

        texto6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        texto6.setForeground(new java.awt.Color(204, 204, 204));
        texto6.setText("MOTORES");
        dashboard.add(texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 70, -1));

        productoresMotores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/p2.png"))); // NOI18N
        dashboard.add(productoresMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        ensambladores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/e3.png"))); // NOI18N
        ensambladores.setToolTipText("");
        dashboard.add(ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        despedirPRuedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/despedir.png"))); // NOI18N
        despedirPRuedas.setToolTipText("");
        despedirPRuedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                despedirPRuedasMouseClicked(evt);
            }
        });
        dashboard.add(despedirPRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, -1));

        despedirPParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/despedir.png"))); // NOI18N
        despedirPParabrisas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                despedirPParabrisasMouseClicked(evt);
            }
        });
        dashboard.add(despedirPParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 190, -1));

        despedirPMotores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/despedir.png"))); // NOI18N
        despedirPMotores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                despedirPMotoresMouseClicked(evt);
            }
        });
        dashboard.add(despedirPMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        contratarPParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/contratar.png"))); // NOI18N
        contratarPParabrisas.setBorder(null);
        contratarPParabrisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPParabrisasActionPerformed(evt);
            }
        });
        dashboard.add(contratarPParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        contratarPRuedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/contratar.png"))); // NOI18N
        contratarPRuedas.setBorder(null);
        contratarPRuedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPRuedasActionPerformed(evt);
            }
        });
        dashboard.add(contratarPRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        contratarPMotores.setBackground(null);
        contratarPMotores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/contratar.png"))); // NOI18N
        contratarPMotores.setBorder(null);
        contratarPMotores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPMotoresActionPerformed(evt);
            }
        });
        dashboard.add(contratarPMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 420, 180, -1));

        despedirEnsambladores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/despedir.png"))); // NOI18N
        despedirEnsambladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                despedirEnsambladoresMouseClicked(evt);
            }
        });
        dashboard.add(despedirEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));

        contratarEnsambladores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/contratar.png"))); // NOI18N
        contratarEnsambladores.setBorder(null);
        contratarEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarEnsambladoresActionPerformed(evt);
            }
        });
        dashboard.add(contratarEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 180, -1));

        gerente.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        gerente.setForeground(new java.awt.Color(255, 255, 255));
        gerente.setText("el gerente está");
        dashboard.add(gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));

        jefe.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jefe.setForeground(new java.awt.Color(255, 255, 255));
        jefe.setText("el jefe está");
        dashboard.add(jefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        estadoJefe.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        estadoJefe.setForeground(new java.awt.Color(255, 255, 255));
        estadoJefe.setText("durmiendo");
        dashboard.add(estadoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        etiqueta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/custom – 1_1.png"))); // NOI18N
        dashboard.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 430, -1));

        gerenteEstado.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        gerenteEstado.setForeground(new java.awt.Color(255, 255, 255));
        gerenteEstado.setText("durmiendo");
        dashboard.add(gerenteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, -1, -1));

        etiqueta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/no-jefe-gerente.png"))); // NOI18N
        dashboard.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        etiqueta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/etiqueta.png"))); // NOI18N
        dashboard.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 260, -1));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/on.png"))); // NOI18N
        start.setBorder(null);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        dashboard.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratarPRuedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPRuedasActionPerformed
        fabrica.contratarProductorR();
        if(fabrica.getCantProductoresR() == fabrica.getMaxProductoresR()){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p4.png")));
            contratarPRuedas.setIcon(new ImageIcon(getClass().getResource("contratar-off.png")));
        }
        if(fabrica.getCantProductoresR() == 1){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p25.png")));
            despedirPRuedas.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantProductoresR() == 2){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p50.png")));
            despedirPRuedas.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantProductoresR() == 3){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p75.png")));
            despedirPRuedas.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        
    }//GEN-LAST:event_contratarPRuedasActionPerformed

    private void contratarEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarEnsambladoresActionPerformed
        fabrica.contratarEnsamblador();
        if(fabrica.getCantEnsambladores() == fabrica.getMaxEnsambladores()){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e5.png")));
            contratarEnsambladores.setIcon(new ImageIcon(getClass().getResource("contratar-off.png")));
        }
        if(fabrica.getCantEnsambladores() == 1){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e1.png")));
            despedirEnsambladores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantEnsambladores() == 2){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e2.png")));
            despedirEnsambladores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantEnsambladores() == 3){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e3.png")));
            despedirEnsambladores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantEnsambladores() == 4){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e4.png")));
            despedirEnsambladores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
    }//GEN-LAST:event_contratarEnsambladoresActionPerformed

    private void despedirPRuedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_despedirPRuedasMouseClicked
        fabrica.despedirProductorR();
        if(fabrica.getCantProductoresR() == 0) {
            despedirPRuedas.setIcon(new ImageIcon(getClass().getResource("despedir-off.png")));
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("no-more.png")));
        }
         if(fabrica.getCantProductoresR() == 1){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p25.png")));
            contratarPRuedas.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantProductoresR() == 2){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p50.png")));
            contratarPRuedas.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantProductoresR() == 3){
            productoresRuedas.setIcon(new ImageIcon(getClass().getResource("p75.png")));
            contratarPRuedas.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
    }//GEN-LAST:event_despedirPRuedasMouseClicked

    private void contratarPParabrisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPParabrisasActionPerformed
        fabrica.contratarProductorP();
        if(fabrica.getCantProductoresP() == fabrica.getMaxProductoresP()){
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("p4.png")));
            contratarPParabrisas.setIcon(new ImageIcon(getClass().getResource("contratar-off.png")));
        }
        if(fabrica.getCantProductoresP() == 1){
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("p2.png")));
            despedirPParabrisas.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantProductoresP() == 2){
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("p3.png")));
            despedirPParabrisas.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
    }//GEN-LAST:event_contratarPParabrisasActionPerformed

    private void contratarPMotoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPMotoresActionPerformed
        fabrica.contratarProductorM();
        if(fabrica.getCantProductoresM() == fabrica.getMaxProductoresP()){
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("p4.png")));
            contratarPMotores.setIcon(new ImageIcon(getClass().getResource("contratar-off.png")));
        }
        if(fabrica.getCantProductoresM() == 1){
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("p2.png")));
            despedirPMotores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
        if(fabrica.getCantProductoresM() == 2){
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("p3.png")));
            despedirPMotores.setIcon(new ImageIcon(getClass().getResource("despedir.png")));
        }
    }//GEN-LAST:event_contratarPMotoresActionPerformed

    private void despedirPParabrisasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_despedirPParabrisasMouseClicked
        fabrica.despedirProductorP();
        if(fabrica.getCantProductoresP() == 0) {
            despedirPParabrisas.setIcon(new ImageIcon(getClass().getResource("despedir-off.png")));
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("no-more.png")));
        }
         if(fabrica.getCantProductoresP() == 1){
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("p2.png")));
            contratarPParabrisas.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantProductoresP() == 2){
            productoresParabrisas.setIcon(new ImageIcon(getClass().getResource("p3.png")));
            contratarPParabrisas.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
    }//GEN-LAST:event_despedirPParabrisasMouseClicked

    private void despedirPMotoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_despedirPMotoresMouseClicked
        fabrica.despedirProductorM();
        if(fabrica.getCantProductoresM() == 0) {
            despedirPMotores.setIcon(new ImageIcon(getClass().getResource("despedir-off.png")));
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("no-more.png")));
        }
         if(fabrica.getCantProductoresM() == 1){
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("p2.png")));
            contratarPMotores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantProductoresM() == 2){
            productoresMotores.setIcon(new ImageIcon(getClass().getResource("p3.png")));
            contratarPMotores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
    }//GEN-LAST:event_despedirPMotoresMouseClicked

    private void despedirEnsambladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_despedirEnsambladoresMouseClicked
        fabrica.despedirEnsamblador();
        if(fabrica.getCantEnsambladores() == 0) {
            despedirEnsambladores.setIcon(new ImageIcon(getClass().getResource("despedir-off.png")));
            ensambladores.setIcon(new ImageIcon(getClass().getResource("no-more.png")));
        }
        if(fabrica.getCantEnsambladores() == 1){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e1.png")));
            contratarEnsambladores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantEnsambladores() == 2){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e2.png")));
            contratarEnsambladores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantEnsambladores() == 3){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e3.png")));
            contratarEnsambladores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
        if(fabrica.getCantEnsambladores() == 4){
            ensambladores.setIcon(new ImageIcon(getClass().getResource("e4.png")));
            contratarEnsambladores.setIcon(new ImageIcon(getClass().getResource("contratar.png")));
        }
    }//GEN-LAST:event_despedirEnsambladoresMouseClicked

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        cont++;
        contratarPRuedas.setVisible(true);
        contratarPParabrisas.setVisible(true);
        contratarPMotores.setVisible(true);
        despedirPRuedas.setVisible(true);
        despedirPParabrisas.setVisible(true);
        despedirPMotores.setVisible(true);
        contratarEnsambladores.setVisible(true);
        despedirEnsambladores.setVisible(true);
        start.setIcon(new ImageIcon(getClass().getResource("off.png")));
        if(cont==1){
            fabrica.startThreads();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    public void inicializarParametros() {
        
        //Inicializar parámetros en la interfaz gráfica
        cantPRuedas.setText(Integer.toString(fabrica.getCantProductoresR()));
        cantPParabrisas.setText(Integer.toString(fabrica.getCantProductoresP()));
        cantPMotores.setText(Integer.toString(fabrica.getCantProductoresM()));
        cantEnsambladores.setText(Integer.toString(fabrica.getCantEnsambladores()));
        cantDias.setText(Integer.toString(fabrica.getCantDias()));
        cantRuedas.setText("0");
        cantParabrisas.setText("0");
        cantMotores.setText("0");
        cantCarros.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantCarros;
    private javax.swing.JLabel cantDias;
    private javax.swing.JLabel cantEnsambladores;
    private javax.swing.JLabel cantMotores;
    private javax.swing.JLabel cantPMotores;
    private javax.swing.JLabel cantPParabrisas;
    private javax.swing.JLabel cantPRuedas;
    private javax.swing.JLabel cantParabrisas;
    private javax.swing.JLabel cantRuedas;
    private javax.swing.JLabel carros;
    private javax.swing.JButton contratarEnsambladores;
    private javax.swing.JButton contratarPMotores;
    private javax.swing.JButton contratarPParabrisas;
    private javax.swing.JButton contratarPRuedas;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel despedirEnsambladores;
    private javax.swing.JLabel despedirPMotores;
    private javax.swing.JLabel despedirPParabrisas;
    private javax.swing.JLabel despedirPRuedas;
    private javax.swing.JLabel dias;
    private javax.swing.JLabel ensambladores;
    private javax.swing.JLabel estadoJefe;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel gerente;
    private javax.swing.JLabel gerenteEstado;
    private javax.swing.JLabel jefe;
    private javax.swing.JLabel motores;
    private javax.swing.JLabel parabrisas;
    private javax.swing.JLabel productoresMotores;
    private javax.swing.JLabel productoresParabrisas;
    private javax.swing.JLabel productoresRuedas;
    private javax.swing.JLabel ruedas;
    private javax.swing.JButton start;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    private javax.swing.JLabel textoCarros;
    // End of variables declaration//GEN-END:variables
}
